name: Flutter Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # Usa la versione del tuo progetto

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer (optional)
        run: flutter analyze

      - name: Run tests
        run: flutter test
